# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-02 08:24
from __future__ import unicode_literals

from django.db import migrations
import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0034_plan_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='stripe_id',
            field=djstripe.fields.StripeIdField(max_length=255),
        ),
    ]
